[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101
lib_deps = 
  adafruit/Adafruit NeoPixel @ ^1.12.0