[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
lib_deps = 
  adafruit/Adafruit VEML7700 Library @ ^2.1.6
  stm32duino/STM32duino VL53L4CX